name: E2E Test Artemis

on:
  workflow_run:
    # Must match the name of build.yml workflow.
    workflows: ["Test Artemis"]
    types: [completed]

jobs:

  server-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    # Save the triggering workflow information as an artifact for later reference
    - name: Save triggering workflow info
      run: |
        echo "TRIGGERING_WORKFLOW_RUN_ID=${{ github.event.workflow_run.id }}" > workflow-context.txt
        echo "TRIGGERING_WORKFLOW_HEAD_BRANCH=${{ github.event.workflow_run.head_branch }}" >> workflow-context.txt
        echo "TRIGGERING_WORKFLOW_HEAD_SHA=${{ github.event.workflow_run.head_sha }}" >> workflow-context.txt
        cat workflow-context.txt
    - name: Upload workflow context
      uses: actions/upload-artifact@v4
      with:
        name: workflow-context
        path: workflow-context.txt        

    - name: Run on pull_request
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      run: echo 'yessss ${{ github.event.workflow_run.pull_requests }}'
    - name: Run on push
      if: ${{ github.event.workflow_run.event != 'pull_request' }}
      run: echo 'push ${{ github.event.workflow_run.pull_requests }}'
    - name: Echo github.event.workflow_run.event
      run: echo '${{ toJSON(github.event.workflow_run.event) }}'
    - name: Echo github.event.workflow_run
      run: echo '${{ toJSON(github.event.workflow_run) }}'
    - name: Echo github.event
      run: echo '${{ toJSON(github.event) }}'
    - name: Echo github.event.workflow_run
      run: echo '${{ toJSON(github.event.workflow_run) }}'

    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Upload Test Results (main)
      if: ${{ github.event.workflow_run.head_branch == 'main' }}
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: artemis-build/test-results/results.xml


    - name: Upload Test Results (branch)
      if: ${{ github.event.workflow_run.head_branch != 'main' }}
      uses: actions/upload-artifact@v4
      with:
        name: JUnit Test Results
        path: artemis-build/test-results/result-branch.xml
